export const actionTypes = {
  SELECT_DATE: 'SELECT_DATE',
  SET_MONTH: 'SET_MONTH',
  UPDATE_NOW: 'UPDATE_NOW',
  GO_TO_TODAY: 'GO_TO_TODAY',
  ADD_TASK: 'ADD_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  EDIT_TASK: 'EDIT_TASK',
}
